version: '3'
services:
  mysql-db:
    build: ./database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'vending_machine'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: "superadmin"
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - vending-machine-db:/var/lib/mysql

  backend:
    build: ./backend
    container_name: vending-machine-backend
    environment:
      - DB_SERVER=mysql-db
    ports:
      - 7707:7707
    depends_on:
      - mysql-db

  frontend:
    build: ./frontend
    container_name: vending-machine-frontend
    environment:
      - BACKEND_HOST="http://203.151.164.229:7707"
    ports:
      - 3000:80
    depends_on:
      - backend


volumes:
  vending-machine-db: